# Generated by Django 4.2.2 on 2023-10-09 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='Question_no',
            field=models.IntegerField(default=1),
        ),
    ]
