# Generated by Django 4.2.2 on 2023-10-09 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0002_question_question_no'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='Question_no',
        ),
    ]
