# Generated by Django 4.2.2 on 2023-10-09 12:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0004_question_question_no'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='choice_number',
            field=models.PositiveIntegerField(default=2),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='question',
            name='option_count',
            field=models.IntegerField(default=4),
        ),
    ]
