# Generated by Django 4.2.2 on 2023-10-11 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0006_rename_answer_answeroption'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('email_id', models.CharField(max_length=200)),
                ('Roll_no', models.IntegerField(default=0)),
            ],
        ),
    ]
