# Generated by Django 4.2.2 on 2023-10-11 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthQuestEngage', '0007_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOtherInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('MiddleName', models.CharField(max_length=200)),
                ('PhoneNumber', models.BigIntegerField()),
                ('DateofBirth', models.DateField()),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=200)),
                ('Address', models.CharField(max_length=200)),
                ('City', models.CharField(max_length=200)),
                ('Pincode', models.IntegerField()),
                ('Primarycare', models.CharField(choices=[('Dr.John Smith', 'Dr.John Smith'), ('Dr.Jane Doe', 'Dr.Jane Doe'), ('Dr.Michael Brown', 'Dr.Michael Brown')], max_length=200)),
                ('KnownAllergies', models.CharField(choices=[('Peanut Allergy', 'Peanut Allergy'), ('Dairy Allergy', 'Dairy Allergy'), ('Gluten Intolerance', 'Gluten Intolerance')], max_length=200)),
                ('CurrentMedications', models.CharField(choices=[('Peanut Allergy', 'Peanut Allergy'), ('Dairy Allergy', 'Dairy Allergy'), ('Gluten Intolerance', 'Gluten Intolerance')], max_length=200)),
                ('MedicalConditions', models.CharField(choices=[('Peanut Allergy', 'Peanut Allergy'), ('Dairy Allergy', 'Dairy Allergy'), ('Gluten Intolerance', 'Gluten Intolerance')], max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Employee',
        ),
    ]
