# Generated by Django 4.2.2 on 2023-10-11 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0009_alter_userotherinfo_currentmedications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherinfo',
            name='MiddleName',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
