# Generated by Django 4.2.2 on 2023-10-13 09:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0011_userotherinfodoctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotherinfo',
            name='Primarycare',
        ),
    ]
