# Generated by Django 4.2.2 on 2023-10-13 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0013_userotherinfo_primarycare'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userotherinfo',
            name='Primarycare',
        ),
    ]
