# Generated by Django 4.2.2 on 2023-10-13 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0014_remove_userotherinfo_primarycare'),
    ]

    operations = [
        migrations.AddField(
            model_name='userotherinfo',
            name='Primary',
            field=models.CharField(choices=[('kylie', 'kylie'), ('kendal', 'kendal'), ('mbappe', 'mbappe'), ('farhun', 'farhun'), ('vivek', 'vivek'), ('khabib', 'khabib')], default=1, max_length=200),
            preserve_default=False,
        ),
    ]
