# Generated by Django 4.2.2 on 2023-10-13 10:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0015_userotherinfo_primary'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userotherinfo',
            old_name='Primary',
            new_name='Primarycare',
        ),
    ]
