# Generated by Django 4.2.2 on 2023-10-17 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0016_rename_primary_userotherinfo_primarycare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherinfodoctor',
            name='Degrees',
            field=models.CharField(choices=[('Bachelor of Medicine and Bachelor of Surgery', 'Bachelor of Medicine and Bachelor of Surgery'), ('Bachelor of Dental Surgery', 'Bachelor of Dental Surgery'), ('Bachelor of Ayurvedic Medicine and Surgery', 'Bachelor of Ayurvedic Medicine and Surgery')], max_length=200),
        ),
        migrations.AlterField(
            model_name='userotherinfodoctor',
            name='Experience',
            field=models.CharField(choices=[('Less than 1 Year', 'Less than 1 Year'), ('One to two Years', 'One to two Years'), ('Three to five Years', 'Three to five Years'), ('More than 5 Years', 'More than 5 years')], max_length=200),
        ),
    ]
