# Generated by Django 4.2.2 on 2023-10-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0017_alter_userotherinfodoctor_degrees_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherinfo',
            name='Primarycare',
            field=models.CharField(choices=[('kylie', 'kylie'), ('kendal', 'kendal'), ('mbappe', 'mbappe'), ('farhun', 'farhun'), ('vivek', 'vivek'), ('khabib', 'khabib'), ('shakeel', 'shakeel')], max_length=200),
        ),
    ]
