# Generated by Django 4.2.2 on 2023-10-17 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0018_alter_userotherinfo_primarycare'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userotherinfo',
            name='Primarycare',
            field=models.IntegerField(),
        ),
    ]
