# Generated by Django 4.2.2 on 2023-10-18 05:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0019_alter_userotherinfo_primarycare'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppointmentDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Age', models.IntegerField()),
                ('Height', models.IntegerField()),
                ('Weight', models.IntegerField()),
                ('BMI', models.IntegerField()),
                ('Issue', models.CharField(max_length=200)),
                ('Date', models.DateField()),
                ('Start_time', models.TimeField()),
                ('End_time', models.TimeField()),
                ('Comment', models.TextField()),
            ],
        ),
    ]
