# Generated by Django 4.2.2 on 2023-10-18 08:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0021_appointmentdetails_user_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appointmentdetails',
            name='user_id',
        ),
    ]
