# Generated by Django 4.2.2 on 2023-10-18 08:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthQuestEngage', '0022_remove_appointmentdetails_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentdetails',
            name='user_id',
            field=models.ForeignKey(default=50, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
