# Generated by Django 4.2.2 on 2023-10-19 11:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0026_rename_userprofile_userprofilescore'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofilescore',
            old_name='score',
            new_name='scores',
        ),
    ]
