# Generated by Django 4.2.2 on 2023-10-26 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0028_intakeform'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntakeForm',
        ),
    ]
