# Generated by Django 4.2.2 on 2023-10-26 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0030_intakeform'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeform',
            name='therapy',
            field=models.CharField(choices=[('therapy1', 'therapy1'), ('therapy2', 'therapy2'), ('therapy3', 'therapy3'), ('therapy4', 'therapy4')], max_length=255),
        ),
    ]
