# Generated by Django 4.2.2 on 2023-10-26 08:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0031_alter_intakeform_therapy'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IntakeForm',
        ),
    ]
