# Generated by Django 4.2.2 on 2023-10-26 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0033_intakeform'),
    ]

    operations = [
        migrations.RenameField(
            model_name='intakeform',
            old_name='Itchy',
            new_name='Itchy_eyes',
        ),
        migrations.AddField(
            model_name='intakeform',
            name='Itchy_skin',
            field=models.CharField(choices=[('Itchy_yes', 'Itchy_yes'), ('Itchy_no', 'Itchy_no')], default=0, max_length=255),
            preserve_default=False,
        ),
    ]
