# Generated by Django 4.2.2 on 2023-10-26 13:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0034_rename_itchy_intakeform_itchy_eyes_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intakeform',
            name='drugs',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='events',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='illness',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='menstrual',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='mood',
            field=models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')]),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='physical',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='relaxation',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='side_effects',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='support',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='supportive',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
        migrations.AlterField(
            model_name='intakeform',
            name='today',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255),
        ),
    ]
