# Generated by Django 4.2.2 on 2023-10-31 07:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthQuestEngage', '0035_alter_intakeform_drugs_alter_intakeform_events_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReportDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game', models.CharField(choices=[('yes', 'yes'), ('no', 'no'), ('maybe', 'maybe')], max_length=255)),
                ('intake', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('answered', models.CharField(max_length=200)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
