# Generated by Django 4.2.2 on 2023-11-02 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0037_doctordetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reportdetails',
            name='answered',
        ),
    ]
