# Generated by Django 4.2.2 on 2023-11-02 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0038_remove_reportdetails_answered'),
    ]

    operations = [
        migrations.AddField(
            model_name='reportdetails',
            name='question_answered',
            field=models.CharField(choices=[('yes', 'yes'), ('no', 'no')], default=1, max_length=255),
            preserve_default=False,
        ),
    ]
