# Generated by Django 4.2.2 on 2023-11-02 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0039_reportdetails_question_answered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='reportdetails',
            old_name='question_answered',
            new_name='questionnaire_answered',
        ),
    ]
