# Generated by Django 4.2.2 on 2023-11-02 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('HealthQuestEngage', '0040_rename_question_answered_reportdetails_questionnaire_answered'),
    ]

    operations = [
        migrations.CreateModel(
            name='DoctorMoodDiary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mood', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6'), ('7', '7'), ('8', '8'), ('9', '9'), ('10', '10')])),
                ('hours', models.CharField(max_length=255)),
                ('physical', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('relaxation', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('support', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('supportive', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('side_effects', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('illness', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('events', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('menstrual', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('today', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
                ('drugs', models.CharField(choices=[('yes', 'yes'), ('no', 'no')], max_length=255)),
            ],
        ),
    ]
