# Generated by Django 4.2.2 on 2023-11-02 08:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('HealthQuestEngage', '0042_remove_doctormooddiary_side_effects_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctormooddiary',
            name='user_id',
            field=models.ForeignKey(default=49, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
